### ISSUE TITLE
Distinctions, elision, and technical debt

### ISSUE THREAD

**Issue by joshtriplett** [nikomatsakis/rustacean-principles#5]
Capturing some discussions:

If Rust maintains a distinction between things (e.g. ref and non-ref), I don't want to have Rust elide that distinction for me and then hit me with it later; but if Rust eliminates the distinction, and I don't actually need the distinction, I'm more likely to be OK with it.

It's only OK to say "you don't have to care about X" if you really never have to care about X. Otherwise it's tech debt.

I want Rust to keep guard rails that make me feel safer, and more comfortable moving quickly and easily. That doesn't mean I need Rust to keep guard rails that aren't actually meaningful, as long as removing them doesn't make me feel less safe or less comfortable.

**Comment by notriddle** [comment]
Another comparison that comes to mind when it comes to something being "acceptable" difficulty is the idea that there's a difference [between being challenging and being punishing](https://www.youtube.com/watch?v=ea6UuRTjkKs). Forcing someone to guess, then to surprise them later by saying "you chose poorly" is punishing, and what we actually want is for the language to be challenging.
